server:
  port: "${PORT:8080}"
spring:
  application:
    name: spring-secret-manager-reactive
  devtools:
    add-properties: false

aws:
  secrets-manager:
    region: ${AWS_REGION:us-east-1}
    endpoint: ${AWS_ENDPOINT:http://localhost:4566}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
